### ISSUE TITLE
Trying to use this in a vuejs application but i get the error below

### ISSUE THREAD

**Issue by mtshikomba** [schreiben/node-jre#15]
ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'C:\laragon\www\ccm-voyager-app\node_modules\tunnel-agent'
 @ ./node_modules/tunnel-agent/index.js 4:10-24
 @ ./node_modules/request/lib/tunnel.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/node-jre/index.js
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader
/lib/selector.js?type=script&index=0!./resources/assets/js/components/fingerprint-components/Capture.vue
 @ ./resources/assets/js/components/fingerprint-components/Capture.vue
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

What might be the problem?

**Comment by tilmankamp** [comment]
As pointed out in #18, I'll discontinue this project.
