### ISSUE TITLE
Moderate Security Error on npm audit

### ISSUE THREAD

**Issue by NLueg** [schreiben/node-jre#16]
I get a moderate security error when installing this package because of `rmdir`:

![image](https://user-images.githubusercontent.com/48101693/67466368-40b18f00-f647-11e9-9856-20327815b66a.png)

After I looked at `rmdir` I saw, that there wasn't an update for a long time so I would suggest to switch to the `rimraf`-project which does quite the same I guess?
Would be nice if you would think about it.

**Comment by tilmankamp** [comment]
As pointed out in #18, I'll discontinue this project.
