### ISSUE TITLE
Allow optionally install openjdk

### ISSUE THREAD

**Issue by tomasbjerre** [schreiben/node-jre#18]
This lib could switch to openjdk. The downloading procedure would be easier as the download links are easily available at https://jdk.java.net/archive/

 * https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_windows-x64_bin.zip
 * https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_osx-x64_bin.tar.gz
 * https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz

As 1.8 and Oracle is hard coded now, I suggest to quickly fix this with hard coding OpenJDK and 11 here:
https://github.com/schreiben/node-jre/blob/master/index.js#L107

Related to:
https://github.com/shannah/jdeploy/issues/11
https://github.com/tomasbjerre/wiremock-npm/issues/1

**Comment by tilmankamp** [comment]
This is a valid point, and as [njre](https://github.com/raftario/njre) is a better maintained alternative doing just that, I'll discontinue this project now.
