### ISSUE TITLE
Probably too old JRE version

### ISSUE THREAD

**Issue by rroeneman** [schreiben/node-jre#7]
Hi, I was enjoying node-jre and suddenly an error about some timezone module kicked in.
Refreshing Java JRE to 8u152 version manually solved the case.

Until updated, for my use case (currently Windows x64) I could simply install latest version on my machine and copy /bin and /lib folders to the respective locations in the node-jre folder.

Hope this helps and thank you for the usefull module!
Best, R.

**Comment by tilmankamp** [comment]
As pointed out in #18, I'll discontinue this project.
